# This file is part of REANA.
# Copyright (C) 2020, 2022, 2023 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: CI

on: [push, pull_request]

jobs:
  lint-dockerfile:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Dockerfile compliance
        run: docker run -i --rm docker.io/hadolint/hadolint:v2.12.0 < Dockerfile

  build-docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t docker.io/reanahub/reana-auth-vomsproxy .

      - name: Test image
        run: docker run -i --rm docker.io/reanahub/reana-auth-vomsproxy voms-proxy-info 2>&1 | grep "Proxy not found"
